package com.if4b.aplikasi_mesjid;

import java.util.ArrayList;

public class DataMasjid {

    public static String[][] data = new String[][]{
            {"Masjid Agung Sultan Mahmud Badaruddin Jayo Wikramo", "Berdiri sejak pertengahan abad ke-18, Masjid Agung Palembang menjadi satu dari sedikit masjid tertua di Sumatera Selatan. Atapnya berbentuk limas tapi menyerupai kelenteng dengan ornamen warna emas. Menara di dekat masjid berbentuk kerucut seperti tumpeng atau gunungan. Dinding beton yang tebal, pintu, dan pilar-pilar besar penyangga bagian depan masjid serupa bangunan peninggalan kolonial yang berarsitektur Eropa. Masuk ke dalam, Anda akan melihat ruangan shalat serupa masjid-masjid kuno di Jawa. Ada pilar-pilar utama dan penyangga menopang atap. Pilar-pilar ini terbuat dari kayu berwarna hijau dengan ukiran motif di bagian bawahnya. Di tengah-tengah, lampu gantung menyinari seisi ruangan. Di dekat mihrab, terdapat mimbar yang dihiasi ukiran khas Palembang. Masjid Agung Sultan Mahmud Badaruddin I (SMB I) Jayo Wikramo atau dikenal dengan Masjid Agung Palembang memang menawan. Selain menampilkan perpaduan arsitektur Tiongkok, Eropa, dan Nusantara, masjid ini merupakan saksi bisu sejarah Kota Palembang.", "https://indonesiakaya.com/wp-content/uploads/2020/10/Masjid_agung_palembang_1200.jpg"},
            {"Masjid Muhammad Cheng Hoo", "Dibangun komunitas Tionghoa-Muslim dengan memadukan tiga kebudayaan yang berbeda. Dari kejauhan, masjid di Palembang ini terlihat begitu mencolok. Bangunan utamanya didominasi warna pink dengan pilar-pilar berwarna merah. Atapnya terdapat kubah berwarna hijau dengan bulan sabit dan bintang layaknya masjid-masjid di Timur Tengah. Sementara di keempat sudut bangunan terdapat atap berbentuk limas, salah bentuk rumah adat di Palembang, berwarna hijau. Masjid dilengkapi dua menara serupa pagoda berwana merah, yang masing-masing diberi nama “Habluminallah” dan “Hambluminannas” –”hubungan manusia dengan Allah” dan “hubungan dengan sesama manusia”. Kedua menara itu punya lima tingkat, yang melambangkan shalat lima waktu dalam sehari. Tinggi menara mencapai 17 meter; simbol dari jumlah rakaat yang harus dikerjakan setiap Muslim dalam sehari. Di lantai dasar masing-masing menara terdapat tempat wudhu. Sementara bagian luar menara dibubuhi ornamen khas Palembang berupa tanduk kambing. Di dalam masjid, pengunjung akan mendapati warna dominan merah yang identik dengan budaya Tionghoa. Desain daun pintu utama, pancang-pancang, dan ornamen pagar pembatas di bagian atas kian mempercantik tampilan interior masjid yang kental nuansa Tionghoa. Di gerbang atau gapura masjid yang bergaya Tiongkok, dengan pilar merah dan atap limas berwarna kuning emas, terdapat sebuah papan nama bertuliskan “Masjid Muhammad Cheng Hoo”, lengkap dengan aksara Mandarin.", "https://indonesiakaya.com/wp-content/uploads/2020/10/Masjid_Cheng_Ho_12001.jpg"},
            {"Masjid Kiai Marogan", "Masjid Kiai Muara Ogan  atau akrab dengan nama Masjid Ki Marogan terletak di pinggiran sungai Musi dan sungai Muara Ogan Seberang Ulu Kertapati. Masjid ini dibangun oleh seorang ulama yang bernama Kiai Masagus Haji Abdul Hamid bin Mahmud alias Kiai Marogan pada tahun 1871 Masehi. Masjid ini unik karena Kiai marogan mendirikannya di titik pertemuan antara dua sungai, yaitu Sungai Ogan dan Sungai Musi. Selain letaknya, masjid ini punya desain yang khas berupa kubah berbentuk limas dengan plafon masjid yang tinggi. Kubah khas ini ternyata sempat mengalami beberapa kali perubahan bentuk selama renovasi.", "https://t-2.tstatic.net/tribunsumseltravel/foto/bank/images/masjid-ki-marogan-palembang1.jpg"},
            {"Masjid Lawang Kidul", "Masjid Lawang Kidul termasuk salah satu masjid tertua di Palembang, Sumatra Selatan. Masjid ini berdiri pada tahun 1881 dan memegang peran penting baik sebagai pusat penyebaran Islam maupun dijadikan markas para pejuang setempat pada masanya. Material Masjid ini terbuat dari campuran batu kapur dengan putih telur dan pasir, sehingga membuat masjid ini dapat bertahan dengan lama. Bangunan induk masjid ini sebagian besar tetap terjaga keasliannya dan hampir 99 persen masih merupakan bangunan asli dan belum ada yang diganti.", "https://cdns.klimg.com/merdeka.com/i/w/news/2021/07/09/1328078/670x335/masjid-lawang-kidul-saksi-perjuangan-rakyat-palembang-lawan-kolonial.jpeg"},
            {"Masjid Al-Mahmudiyah Suro", "Masjid Besar Al-Mahmudiyah atau Masjid Suro adalah salah satu masjid tertua di kota Palembang. Masjid ini berlokasi di jalan Jalan Ki Gede Ing Suro, Kelurahan 30 Ilir, Kecamatan Ilir Barat II, Palembang, Sumatra Selatan. Dibangun oleh seorang ulama besar, KH Abdurahman Delamat (Ki Delamat) di atas tanah wakaf milik Kiai Kiagus H Khotib Mahmud tahun 1889 dan selesai tahun 1991. Masjid unik dengan ciri khas melayu ini, awalnya disebut dengan nama Masjid Suro. Lalu Kiagus H. Matjik Rosad, cucu dari Kiagus H Khotib Mahmud mengusulkan nama Al-Mahmudiyah, hingga akhirnya jadilah nama Al-Mahmudiyah.", "https://duniamasjid.islamic-center.or.id/wp-content/uploads/2014/05/masjid-besar-al-mahmudiyah-palembang.jpg"},
            {"Masjid Istiqomah", "Masjid ini awalnya berada di jalan Merdeka, tepat di depan kantor walikota Palembang. Namun seiring dengan perkembangan kota yang makin pesat maka masjid yang di dirikan tahun 1960 ini kemudian di relokasi. Tidak jauh dari lokasi awal, sekitar 250m. Dilokasi baru sekarang sudah tersedia halaman parkir mobil yang luas di sayap kiri dan motor di sayap kanan. Diresmikan oleh walikota Harnojoyo pada bulan Desember 2021 bersama dengan Ustad Abdul Somad.", "https://app.syiar.id/foto/aset/29ed2e1f-0e3d-46c4-be32-aaaf2d2bf9d2.jpg"},
            {"Masjid Daarul Jannah", "Masjid ini dikenal juga dengan nama 'Masjid Darul Jannah Rawajaya' .Diresmikan oleh walikota Palembang , Ir.H.Eddy Santana Putra, MT pada hari Jum'at, tanggal 1 Desember 2006.", "https://app.syiar.id/foto/aset/9c5e198b-02e1-42b0-a425-96f66b2f00f4.jpg"},
            {"Masjid As-Salam", "Masjid As-Salam yang dibangun pada tahun 2000. Masjid As-Salam merupakan kategori masjid Umum. Masjid As-Salam memiliki luas tanah 169m2 dengan status tanah Wakaf. Masjid As-Salam memiliki jumlah jamaah 150-200 orang.", "https://app.syiar.id/foto/aset/d5248a0a-c1ac-49be-868b-0a3d4a3d62c2.jpg"},
            {"Masjid Al-Firdaus", "Masjid Al-Firdaus yang dibangun pada tahun 1975. Masjid Al-Firdaus merupakan kategori masjid Umum. Masjid Al-Firdaus memiliki luas tanah 169m2 dengan status tanah Wakaf. Masjid Al-Firdaus memiliki jumlah jamaah 150-200 orang.", "https://app.syiar.id/foto/aset/a412930c-0c0c-46a7-beaa-f41dc415d946.jpeg"},
            {"Masjid Al-Ghaniy", "Masjid Al-Ghaniy yang dibangun pada tahun 1975. Masjid Al-Ghaniy merupakan kategori masjid Umum. Masjid Al-Ghaniy memiliki luas tanah 169m2 dengan status tanah Wakaf. Masjid Al-Ghaniy memiliki jumlah jamaah 200-250 orang.", "https://hallo.palembang.go.id/petalokasi/login/assets/file/gambar/Masjid_Al-Ghaniy.jpg"},
    };

    public static ArrayList<ModelMasjid> ambilDataMasjid() {
        ArrayList<ModelMasjid> dataMasjid = new ArrayList<>();
        for (String[] varData : data) {
            ModelMasjid model = new ModelMasjid();
            model.setNama(varData[0]);
            model.setTentang(varData[1]);
            model.setFoto(varData[2]);

            dataMasjid.add(model);
        }

        return dataMasjid;
    }

}
